apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-bridge
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: alert-bridge
  template:
    metadata:
      labels:
        app: alert-bridge
    spec:
      containers:
        - name: alert-bridge
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: LEXCODE_GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: alert-bridge-secrets
                  key: LEXCODE_GITHUB_TOKEN
            - name: GITHUB_REPO
              valueFrom:
                secretKeyRef:
                  name: alert-bridge-secrets
                  key: GITHUB_REPO
---
