replicaCount: 1

image:
  repository: runner-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

prometheus:
  targets:
    - name: runner
      target: "runner-svc:8000"

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: example.com
      paths:
        - path: /runner
          pathType: Prefix
  tls: []

serviceAccount:
  create: true
  annotations: {}
  name: ""
