apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: {{ include "lexcode.ns" . }}
spec:
  replicas: {{ .Values.replicaCount.gateway }}
  selector: { matchLabels: { app: gateway } }
  template:
    metadata: { labels: { app: gateway } }
    spec:
      containers:
        - name: gateway
          image: {{ .Values.image.gateway }}
          ports: [{ containerPort: 5000 }]
          envFrom: [{ secretRef: { name: lexcode-secrets } }]
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-svc
  namespace: {{ include "lexcode.ns" . }}
spec:
  selector: { app: gateway }
  ports: [{ port: 5000, targetPort: 5000 }]
