{{- if .Values.loki.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: {{ .Values.namespace | default .Release.Namespace }}
data:
  local-config.yaml: |
{{- toYaml .Values.loki.config | nindent 4 }}
{{- end }}
