{{- if .Values.loki.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: {{ .Values.loki.image }}
          args:
            - -config.file=/etc/loki/local-config.yaml
          ports:
            - containerPort: {{ .Values.loki.servicePort }}
          volumeMounts:
            - name: loki-config
              mountPath: /etc/loki
            - name: loki-storage
              mountPath: /loki
      volumes:
        - name: loki-config
          configMap:
            name: loki-config
        - name: loki-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  ports:
    - port: {{ .Values.loki.servicePort }}
      targetPort: {{ .Values.loki.servicePort }}
      protocol: TCP
      name: http
  selector:
    app: loki
{{- end }}
