---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-deployment
  namespace: default
  labels:
    app: top-tier-core
    component: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: top-tier-core
  template:
    metadata:
      labels:
        app: top-tier-core
        component: api
    spec:
      containers:
        - name: core-api
          image: top-tier/core:latest
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: API_HOST
              value: "0.0.0.0"
            - name: API_PORT
              value: "8000"
            - name: ENVIRONMENT
              value: "production"
            - name: NEO4J_URL
              value: "bolt://neo4j-service:7687"
            - name: NEO4J_USER
              valueFrom:
                secretKeyRef:
                  name: neo4j-secret
                  key: NEO4J_USER
            - name: NEO4J_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: neo4j-secret
                  key: NEO4J_PASSWORD
            - name: REDIS_URL
              value: "redis://redis-service:6379"
            - name: POSTGRES_URL
              value: "postgresql://postgres:postgres@postgres-service:5432/app_db"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          # Health Probes
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: core-service
  namespace: default
  labels:
    app: top-tier-core
    component: api
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: top-tier-core
