---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: core-api
  name: core-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: core-api
  template:
    metadata:
      labels:
        app: core-api
    spec:
      containers:
      - env:
        - name: API_HOST
          value: 0.0.0.0
        - name: API_PORT
          value: '8000'
        - name: ENVIRONMENT
          value: production
        - name: NEO4J_URL
          value: bolt://neo4j-service:7687
        - name: NEO4J_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: neo4j-secret
        - name: NEO4J_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: neo4j-secret
        - name: REDIS_URL
          value: redis://redis-service:6379
        - name: POSTGRES_URL
          value: postgresql://postgres:postgres@postgres-service:5432/app_db
        image: top-tier-global-hub-ai:latest
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        name: core-api
        ports:
        - containerPort: 8000
          name: http
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 256Mi
        startupProbe:
          failureThreshold: 10
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: core-api-service
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  selector:
    app: core-api
  type: ClusterIP

