apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-deployment
  labels:
    app: top-tier-hub-core
spec:
  replicas: 2
  selector:
    matchLabels:
      app: top-tier-hub-core
  template:
    metadata:
      labels:
        app: top-tier-hub-core
    spec:
      containers:
      - name: api-server
        image: top-tier-hub-api:latest
        ports:
        - containerPort: 8000
        env:
        - name: API_HOST
          value: "0.0.0.0"
        - name: API_PORT
          value: "8000"
        - name: NEO4J_URL
          value: "bolt://neo4j-service:7687"
        - name: NEO4J_USER
          valueFrom:
            secretKeyRef:
              name: neo4j-credentials
              key: username
        - name: NEO4J_PASSWORD
          valueFrom:
            secretKeyRef:
              name: neo4j-credentials
              key: password
        - name: REDIS_URL
          value: "redis://redis-service:6379/0"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: url
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: core-service
spec:
  selector:
    app: top-tier-hub-core
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP