---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: osint-deployment
  namespace: default
  labels:
    app: top-tier-osint
    component: osint-engine
spec:
  replicas: 2
  selector:
    matchLabels:
      app: top-tier-osint
  template:
    metadata:
      labels:
        app: top-tier-osint
        component: osint-engine
    spec:
      containers:
        - name: osint-engine
          image: top-tier/osint:latest
          ports:
            - containerPort: 8001
              name: http
          env:
            - name: OSINT_HOST
              value: "0.0.0.0"
            - name: OSINT_PORT
              value: "8001"
            - name: ENVIRONMENT
              value: "production"
            - name: NEO4J_URL
              value: "bolt://neo4j-service:7687"
            - name: NEO4J_USER
              valueFrom:
                secretKeyRef:
                  name: neo4j-secret
                  key: NEO4J_USER
            - name: NEO4J_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: neo4j-secret
                  key: NEO4J_PASSWORD
            - name: REDIS_URL
              value: "redis://redis-service:6379/1"
            - name: POSTGRES_URL
              value: "postgresql://postgres:postgres@postgres-service:5432/app_db"
            # OSINT API Keys (should be stored in secrets)
            - name: SHODAN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: osint-secrets
                  key: SHODAN_API_KEY
                  optional: true
            - name: VIRUSTOTAL_API_KEY
              valueFrom:
                secretKeyRef:
                  name: osint-secrets
                  key: VIRUSTOTAL_API_KEY
                  optional: true
            - name: HUNTER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: osint-secrets
                  key: HUNTER_API_KEY
                  optional: true
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          # Health Probes
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 8001
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 45
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 12
---
apiVersion: v1
kind: Service
metadata:
  name: osint-service
  namespace: default
  labels:
    app: top-tier-osint
    component: osint-engine
spec:
  type: ClusterIP
  ports:
    - port: 8001
      targetPort: 8001
      protocol: TCP
      name: http
  selector:
    app: top-tier-osint
---
apiVersion: v1
kind: Secret
metadata:
  name: osint-secrets
  namespace: default
  labels:
    app: top-tier-osint
    component: osint-engine
type: Opaque
stringData:
  # Add your OSINT API keys here
  SHODAN_API_KEY: "your-shodan-api-key-here"
  VIRUSTOTAL_API_KEY: "your-virustotal-api-key-here"
  HUNTER_API_KEY: "your-hunter-api-key-here"
