---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: osint-service
  name: osint-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: osint-service
  template:
    metadata:
      labels:
        app: osint-service
    spec:
      containers:
      - env:
        - name: MINI_WEB_HOST
          value: 0.0.0.0
        - name: MINI_WEB_PORT
          value: '8088'
        - name: MAIN_API_URL
          value: http://core-api-service:8000
        - name: NEO4J_URL
          value: bolt://neo4j-service:7687
        - name: NEO4J_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: neo4j-secret
        - name: NEO4J_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: neo4j-secret
        - name: REDIS_URL
          value: redis://redis-service:6379/1
        - name: API_TOKEN
          valueFrom:
            secretKeyRef:
              key: api-token
              name: osint-secret
              optional: true
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: secret-key
              name: osint-secret
              optional: true
        - name: ENABLE_CACHE
          value: 'true'
        - name: ENABLE_MONITORING
          value: 'true'
        - name: DEBUG
          value: 'false'
        image: veritas-mini-web:latest
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8088
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        name: osint-service
        ports:
        - containerPort: 8088
          name: http
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8088
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 256Mi
        startupProbe:
          failureThreshold: 10
          httpGet:
            path: /health
            port: 8088
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: osint-service
spec:
  ports:
  - name: http
    port: 8088
    targetPort: 8088
  selector:
    app: osint-service
  type: ClusterIP

