from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from typing import List

app = FastAPI(title="RAG Engine", version="0.1.0")


class QueryRequest(BaseModel):
    question: str
    top_k: int = 3


class QueryResponse(BaseModel):
    answer: str
    context: List[str]
    question: str
    top_k: int


def build_mock_response(question: str, top_k: int) -> QueryResponse:
    mock_context = [
        "Context snippet 1 for demonstration purposes.",
        "Context snippet 2 offering additional details.",
    ][:top_k]
    return QueryResponse(
        answer="This is a mock RAG answer generated by the bootstrap service.",
        context=mock_context,
        question=question,
        top_k=top_k,
    )


@app.get("/health", response_model=dict)
def health() -> dict:
    return {"status": "ok"}


@app.post("/query", response_model=QueryResponse)
def query(request: QueryRequest) -> QueryResponse:
    if not request.question:
        raise HTTPException(status_code=400, detail="Question must not be empty.")
    return build_mock_response(request.question, request.top_k)


if __name__ == "__main__":
    import uvicorn

    uvicorn.run("app:app", host="0.0.0.0", port=8081, reload=False)
