apiVersion: apps/v1
kind: Deployment
metadata:
  name: runner-deploy
  labels:
    {{- include "runner-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "runner-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "runner-service.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "runner-service.serviceAccountName" . }}
      containers:
        - name: runner
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          livenessProbe:
            httpGet:
              path: /health
              port: http
          env: []
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
