name: API Routes Test

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install newman
        run: npm install -g newman

      - name: Run Gateway
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          nohup node server.js > server.log 2>&1 &
          sleep 5

      - name: Run Postman tests
        run: |
          newman run ops/api_collection.postman.json \
            --env-var base_url=http://localhost:3000
