name: CodeX System Check

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  system-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y jq netcat
      - name: Run CodeX System Check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REF: ${{ github.ref }}
        run: bash .github/scripts/codex-system-check.sh
