name: Deploy to GHCR
on:
  push:
    branches: [ main, master ]
    paths:
      - 'Dockerfile'
      - 'api_server.py'
      - 'veritas_console.py'
      - '.github/workflows/Deploy-GHCR.yml'
  workflow_dispatch:
permissions:
  contents: read
  packages: write
env:
  IMAGE_NAME: veritas-console
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
