---
name: Immutable-Release
'on':
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: write
  packages: write

env:
  IMAGE_NAME: veritas-console

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # بناء الحاوية + نشرها إلى ghcr.io
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}

      # توليد Checksum للإخراج (يوثق سلامة الإصدار)
      - name: Generate checksum
        run: |
          echo "{}" > release.json
          tar czf src.tgz $(git ls-files)
          sha256sum src.tgz > SHA256SUMS

      # إنشاء إصدار GitHub وإرفاق الملفات
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            SHA256SUMS
            src.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  mirror:
    needs: build-release
    runs-on: ubuntu-latest
    steps:
      - name: Warn when mirror deployment secrets are missing
        if: ${{ secrets.MIRROR_URL == '' || secrets.MIRROR_DEPLOY_KEY == '' || secrets.MIRROR_HOST == '' }}
        run: |
          echo "Mirror push skipped: mirroring secrets are missing." >&2
          echo "Set MIRROR_URL, MIRROR_DEPLOY_KEY, and MIRROR_HOST to enable mirroring." >&2

      - uses: actions/checkout@v4
        if: ${{ secrets.MIRROR_URL != '' && secrets.MIRROR_DEPLOY_KEY != '' && secrets.MIRROR_HOST != '' }}

      - name: Configure mirror key
        if: ${{ secrets.MIRROR_URL != '' && secrets.MIRROR_DEPLOY_KEY != '' && secrets.MIRROR_HOST != '' }}
        run: |
            install -m 600 -D /dev/null ~/.ssh/id_ed25519
            echo "${{ secrets.MIRROR_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
            {
              echo "Host mirror"
              echo "  Hostname ${{ secrets.MIRROR_HOST }}"
              echo "  IdentityFile ~/.ssh/id_ed25519"
              echo "  StrictHostKeyChecking no"
            } > ~/.ssh/config

      - name: Push mirror
        if: ${{ secrets.MIRROR_URL != '' && secrets.MIRROR_DEPLOY_KEY != '' && secrets.MIRROR_HOST != '' }}
        run: |
          git remote add mirror "${{ secrets.MIRROR_URL }}"
          git push mirror --tags
