name: Veritas Nexus • Health (Auto)

on:
  push:
    branches: [ main, develop ]
  pull_request:
  schedule:
    - cron: "*/30 * * * *"   # تلقائي كل 30 دقيقة (UTC)
  # لا تشغيل يدوي هنا (لا workflow_dispatch)، كل شيء تلقائي

jobs:
  health-check:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      # استهداف محلي (docker-compose) بشكل افتراضي
      CORE_URL: http://localhost:8000
      OSINT_URL: http://localhost:8080
      NEO4J_HTTP: http://localhost:7474
      NEO4J_USER: ${{ secrets.NEO4J_USER }}
      NEO4J_PASS: ${{ secrets.NEO4J_PASS }}
      # لو عندك فحص عبر Services داخل K8s، وفّرت kubeconfig كسِر
      KUBECONFIG_B64: ${{ secrets.KUBECONFIG_B64 }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq netcat-openbsd

      - name: Auto-select K8s Services if kubeconfig is provided
        if: ${{ env.KUBECONFIG_B64 != '' }}
        run: |
          echo "$KUBECONFIG_B64" | base64 -d > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
          # استهدف Services داخل الكلاستر بدل localhost
          echo "CORE_URL=http://veritas-core-svc"      >> $GITHUB_ENV
          echo "OSINT_URL=http://osint-engine-svc:8081" >> $GITHUB_ENV
          echo "NEO4J_HTTP=http://neo4j:7474"           >> $GITHUB_ENV

      - name: Show targets
        run: |
          echo "CORE_URL=$CORE_URL"
          echo "OSINT_URL=$OSINT_URL"
          echo "NEO4J_HTTP=$NEO4J_HTTP"

      - name: Make script executable
        run: chmod +x scripts/veritas_health_check.sh

      - name: Start local services if using localhost
        if: ${{ env.KUBECONFIG_B64 == '' }}
        run: |
          echo "Starting local services via docker compose..."
          
          # Create minimal environment for testing
          cp .env.example .env 2>/dev/null || echo "# Test environment" > .env
          echo "ENVIRONMENT=ci" >> .env
          echo "DEBUG=false" >> .env
          
          # Create Neo4j env file if needed
          sudo mkdir -p /opt/veritas || true
          if [ ! -f /opt/veritas/.env.neo4j ]; then
            sudo tee /opt/veritas/.env.neo4j > /dev/null << EOF
          NEO4J_AUTH=neo4j/testpassword123
          NEO4J_AUTH_USER=neo4j
          NEO4J_AUTH_PASSWORD=testpassword123
          NEO4J_DATABASE=neo4j
          EOF
          fi
          
          # Start only the services we need for health checking
          echo "Starting API service..."
          timeout 300 docker compose up -d api || echo "API failed to start"
          
          echo "Starting veritas-web service..."
          timeout 300 docker compose --profile mini-web up -d veritas-web || echo "Veritas-web failed to start"
          
          # Wait for services to be ready
          echo "Waiting for services to start..."
          sleep 30
          
          echo "Service status:"
          docker compose ps || true

      - name: Run health checks (with retry)
        id: runcheck
        run: |
          set -o pipefail
          attempt() {
            echo "== Veritas Health Check Attempt $1 ($(date -u +%FT%TZ)) =="
            ./scripts/veritas_health_check.sh
          }
          # محاولتان تلقائيًا لتجاوز أي تعثر مؤقت
          attempt 1 2>&1 | tee health.log || (sleep 10 && attempt 2 2>&1 | tee -a health.log)

      - name: Upload health log
        if: ${{ success() || failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: veritas-health-log
          path: health.log
          retention-days: 7

      - name: Cleanup services
        if: ${{ always() && env.KUBECONFIG_B64 == '' }}
        run: |
          echo "Cleaning up local services..."
          docker compose down -v --remove-orphans || true
          docker system prune -f || true

      - name: Job summary
        if: ${{ success() || failure() }}
        run: |
          if [ "${{ job.status }}" = "success" ]; then
            echo "### ✅ Health Check: **PASSED**" >> $GITHUB_STEP_SUMMARY
            echo "- Core/OSINT/Neo4j جميعها تعمل." >> $GITHUB_STEP_SUMMARY
          else
            echo "### ❌ Health Check: **FAILED**" >> $GITHUB_STEP_SUMMARY
            echo "- راجع Artifact: **veritas-health-log**." >> $GITHUB_STEP_SUMMARY
          fi

      # فتح Issue تلقائي عند الفشل
      - name: Open Issue on failure
        if: ${{ failure() }}
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            let tail = 'log unavailable';
            try {
              tail = fs.readFileSync('health.log','utf8').split('\n').slice(-120).join('\n');
            } catch(e) {}
            const title = `❌ Veritas Health Failed – ${new Date().toISOString()}`;
            const body = [
              'Health check failed.',
              `Run: https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`,
              `Commit: ${context.sha}`,
              '',
              '#### Tail of health.log',
              '```',
              tail,
              '```'
            ].join('\n');
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title,
              body,
              labels: ['health-check','automation','bug']
            });

      # إغلاق أي Issues مفتوحة للصحة تلقائيًا عند النجاح
      - name: Auto-close health issues on success
        if: ${{ success() }}
        uses: actions/github-script@v7
        with:
          script: |
            const issues = await github.paginate(github.rest.issues.listForRepo, {
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: 'health-check'
            });
            for (const i of issues) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: i.number,
                body: `✅ Health restored in run https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`
              });
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: i.number,
                state: 'closed'
              });
            }
