---
name: veritas-health
on:
  workflow_dispatch:

concurrency:
  group: veritas-health
  cancel-in-progress: true

jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run health check and save log (do not fail before upload)
        id: run_check
        run: |
          set -o pipefail
          # تأكد أن سكربت الفحص موجود ويكتب health.log في جذر الـ workspace
          if [ -x ./scripts/health-check.sh ]; then
            ./scripts/health-check.sh > health.log 2>&1 || true
          else
            echo "No health-check script found, producing placeholder log" > health.log
          fi
        continue-on-error: true

      - name: Ensure any nested logs are collected
        run: |
          # اجعل البحث أوسع عن health.log في المسارات الفرعية إن وُجد
          find . -type f -name "health.log" -maxdepth 6 -print || true

      - name: Upload health log artifact
        uses: actions/upload-artifact@v4
        with:
          name: veritas-health-log
          path: |
            health.log
            **/health.log

      - name: "Optional: report status (keeps job non-failing after upload)"
        run: |
          if grep -i "error\|failed\|exception" health.log >/dev/null 2>&1; then
            echo "Health check detected issues. See veritas-health-log artifact."
            # لإجبار فشل الـ job بعد الرفع، أزل التعليق من السطر التالي:
            # exit 1
          else
            echo "Health check looks OK."
          fi
