name: Veritas Health Check

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  health-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || true

      - name: Start services (Docker Compose)
        run: docker compose up -d --build

      - name: Wait for services to start
        run: sleep 30

      - name: Run health check script
        run: bash scripts/veritas_health_check.sh | tee health.log

      - name: Upload health log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: veritas-health-log
          path: health.log

      - name: Shutdown services
        if: always()
        run: docker compose down
